export const actionTypes = {
    CHANGE_SIZE_COLUMNS_CELLS_AREA: 'LIFE:CHANGE_SIZE_COLUMNS_CELLS_AREA',
    CHANGE_SIZE_ROWS_CELLS_AREA: 'LIFE:CHANGE_SIZE_ROWS_CELLS_AREA',
    CHANGE_AREA_CELLS: 'LIFE:CHANGE_AREA_CELLS',
    CHANGE_ACTIVE_STATE_CELL: 'LIFE:CHANGE_ACTIVE_STATE_CELL',
    TRIGGER_ONE_CYCLE_LIFE: 'LIFE:TRIGGER_ONE_CYCLE_LIFE',
    START_GAME: 'LIFE:START_GAME',
    STOP_GAME: 'LIFE:STOP_GAME',
};